server:
  http_listen_address: 0.0.0.0
  http_listen_port: 3100
  http_server_read_timeout: 5m
  http_server_write_timeout: 5m
  grpc_server_max_recv_msg_size: 8388608
  grpc_server_max_send_msg_size: 8388608

memberlist:
  join_members: ["loki-read", "loki-write", "loki-backend"]
  dead_node_reclaim_time: 30s
  gossip_to_dead_nodes_time: 15s
  left_ingesters_timeout: 30s
  bind_addr: ['0.0.0.0']
  bind_port: 7946
  gossip_interval: 2s

schema_config:
  configs:
    - from: 2021-08-01
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: index_
        period: 24h

common:
  path_prefix: /loki
  replication_factor: 1
  compactor_address: http://backend-loki.logs:3100
  storage:
    s3:
      endpoint: minio.logs:9010
      insecure: true
      bucketnames: loki-data
      access_key_id: ${MINIO_ROOT_USER}
      secret_access_key: ${MINIO_ROOT_PASSWORD}
      s3forcepathstyle: true
  ring:
    kvstore:
      store: memberlist
    replication_factor: 1

limits_config:
  reject_old_samples: false
  reject_old_samples_max_age: 30d
  ingestion_rate_mb: 16
  ingestion_burst_size_mb: 32

ruler:
  storage:
    s3:
      bucketnames: loki-ruler

compactor:
  working_directory: /tmp/compactor
